name = ["Yash","Prakhar","Ajay","Vansh"]
rollno = [5,8,6,1]
print(name)
name.extend(rollno)
print(name)
name.append("Hello")
print(name)
name.insert(1,"Rohan")
print(name)
name.remove(8)
print(name)
name.pop()
print(name)
print(name.index("Vansh"))
name.append(5)
print(name.count(5))
rollno.sort()
print(rollno)
name.reverse()
print(name)
newname= name.copy()
print(newname)
name.clear()
print(name)
